#!/usr/bin/env python3
# Mini clawd sprite -> a single RGB565 C header (src/anims/clawd_mini.h), used by
# the small clawds that visualize subagents. Source: out/clawd_south.png, cropped
# by alpha, fitted to MINI and composited onto the device background — so the
# device needs no transparency, it just erases with BG and redraws.
#
#   python3 tools/pixellab/06_mini.py
import os
from PIL import Image

BG = (36, 39, 44)   # must match BG_R/G/B in include/config.h
MINI = 40           # mini clawd size (px)
SRC = "out/clawd_south.png"
OUT = "out/clawd_mini.h"
NAME = "clawd_mini"


def to565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


im = Image.open(SRC).convert("RGBA")

# 1) crop to the alpha bounds
bbox = im.getbbox()
if bbox:
    im = im.crop(bbox)

# 2) pad to a square, preserving the aspect ratio
w, h = im.size
side = max(w, h)
sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
sq.paste(im, ((side - w) // 2, (side - h) // 2))

# 3) downscale to MINI (LANCZOS keeps the blocky character clean)
sq = sq.resize((MINI, MINI), Image.LANCZOS)

# 4) composite onto the device background so edge anti-aliasing blends in
bg = Image.new("RGBA", sq.size, BG + (255,))
rgb = Image.alpha_composite(bg, sq).convert("RGB")

px = rgb.load()
vals = [to565(*px[x, y]) for y in range(MINI) for x in range(MINI)]

with open(OUT, "w") as f:
    f.write(f"// mini clawd (subagent mascot): {MINI}x{MINI}, RGB565.\n")
    f.write("// Generated by: python3 tools/pixellab/06_mini.py (source out/clawd_south.png)\n")
    f.write("#pragma once\n#include <Arduino.h>\n")
    f.write(f"#define CLAWD_MINI_W {MINI}\n#define CLAWD_MINI_H {MINI}\n")
    f.write(f"static const uint16_t {NAME}[CLAWD_MINI_W*CLAWD_MINI_H] = {{")
    f.write(",".join(f"0x{v:04X}" for v in vals))
    f.write("};\n")

print(f"wrote {OUT}  ({MINI}x{MINI}, ~{MINI*MINI*2//1024} KB flash)")
